# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

# 네이버 지도 Legacy 소스 추가
source 'https://github.com/navermaps/NMapsMapLegacySpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'Runnect-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
  pod 'NMapsMap-Legacy'
  pod 'Kingfisher', '~> 7.0'
  pod 'SnapKit', '~> 5.6.0'
  pod 'Moya', '~> 15.0'
  pod 'Then'
  pod 'KakaoSDKCommon'
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKUser'
  pod 'KakaoSDKShare'
  pod 'KakaoSDKTemplate'
  pod 'FirebaseDynamicLinks'
  pod 'KakaoSDKTalk'
  pod 'DropDown', :git => 'https://github.com/thingineeer/DropDown.git', :commit => '95ee36f7bd925d466033c2c169979f1c574bf3b9'
  pod 'CombineCocoa'
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'Firebase/RemoteConfig'	
end

# Pods for Runnect-iOS

post_install do |installer|
  # IPHONEOS_DEPLOYMENT_TARGET 설정
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end

  # BoringSSL-GRPC 경고 제거
  installer.pods_project.targets.each do |target|
    if target.name == 'BoringSSL-GRPC'
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          flags = file.settings['COMPILER_FLAGS'].split
          flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
          file.settings['COMPILER_FLAGS'] = flags.join(' ')
        end
      end
    end
  end

  # Bitcode 제거 스크립트 추가
  bitcode_strip_path = `xcrun --find bitcode_strip`.chop!
  def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
    framework_path = File.join(Dir.pwd, framework_relative_path)
    command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
    puts "Stripping bitcode: #{command}"
    system(command)
  end

  # 정확한 경로 반영
  framework_paths = [
    # NMapsMap 경로
    "Pods/NMapsMap-Legacy/framework/NMapsMap.xcframework/ios-arm64/NMapsMap.framework/NMapsMap",
    "Pods/NMapsMap-Legacy/framework/NMapsMap.xcframework/ios-arm64_x86_64-simulator/NMapsMap.framework/NMapsMap",

    # NMapsGeometry 경로
    "Pods/NMapsGeometry/framework/NMapsGeometry.xcframework/ios-arm64/NMapsGeometry.framework/NMapsGeometry",
    "Pods/NMapsGeometry/framework/NMapsGeometry.xcframework/ios-arm64_x86_64-simulator/NMapsGeometry.framework/NMapsGeometry"
  ]

  framework_paths.each do |framework_relative_path|
    strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
  end
end